run: build
	java team11.helloex.Hello
build:
	"C:\Program Files\Java\jdk1.8.0_45\bin\javac" team11\helloex\Hello.java
	"C:\Program Files\Java\jdk1.8.0_45\bin\javac" team11\helloex\Printer.java
clean: 
	$(RM) team11\helloex\*.class